package:
  name: dotnet-source-8
  version: 8.0.10
  epoch: 1
  description: ".NET SDK"
  copyright:
    - license: MIT
  resources:
    cpu: 2
    memory: 32Gi
  dependencies:
    runtime:
      - icu

environment:
  contents:
    packages:
      - bash
      - build-base
      - busybox
      - ca-certificates-bundle
      - clang-15
      - clang-15-default
      - cmake
      - curl
      - glibc-locale-en
      - icu-dev
      - krb5-dev
      - libunwind-dev
      - llvm15
      - llvm15-cmake-default
      - llvm15-dev
      - llvm15-tools
      - lttng-ust-dev
      - ncurses-dev
      - openssl-dev
      - python3
      - samurai
      - wolfi-base
      - zlib-dev
      - dotnet-bootstrap-8

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dotnet/dotnet
      tag: v${{package.version}}
      expected-commit: 8922fe64a1903ed4e35e24568efb056b3e0fad43
      destination: /home/build/src

  - working-directory: /home/build/src
    pipeline:
      - runs: |
          sed -i -E 's|( /p:BuildDebPackage=false)|\1 /p:EnablePackageValidation=false|' src/runtime/eng/SourceBuild.props
          sed -i -E 's|( /p:BuildDebPackage=false)|\1 --cmakeargs -DCLR_CMAKE_USE_SYSTEM_LIBUNWIND=TRUE|' src/runtime/eng/SourceBuild.props
          ln -sf /usr/share/dotnet-bootstrap/dotnet .dotnet
          mkdir -p prereqs/packages/archive/
          ln -sf /usr/share/dotnet-bootstrap/Private.SourceBuilt.Artifacts.Bootstrap.tar.gz prereqs/packages/archive/Private.SourceBuilt.Artifacts.Bootstrap.tar.gz
      - runs: |
          ./build.sh --clean-while-building \
            -- \
            /v:n \
            /p:ContinueOnPrebuiltBaselineError=true \
            /p:MinimalConsoleLogOutput=false \
            /p:SkipPortableRuntimeBuild=true \
            /p:BuildWithOnlineSources=false
      - runs: |
          mkdir -p "${{targets.destdir}}"/usr/share/dotnet-source
          mkdir -p "${{targets.destdir}}"/usr/bin
      - assertions:
          required-steps: 1
        pipeline:
          - if: ${{build.arch}} == 'aarch64'
            runs: |
              tar zxf artifacts/arm64/Release/dotnet-sdk-*.tar.gz -C "${{targets.destdir}}"/usr/share/dotnet-source
          - if: ${{build.arch}} == 'x86_64'
            runs: |
              tar zxf artifacts/x64/Release/dotnet-sdk-*.tar.gz -C "${{targets.destdir}}"/usr/share/dotnet-source
      - runs: |
          ln -s /usr/share/dotnet-source/dotnet "${{targets.destdir}}"/usr/bin/dotnet

  - uses: strip

subpackages:
  - name: dotnet-source-8-runtime
    description: "The .NET Core Runtime, version 8"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/dotnet-source/shared
          mv "${{targets.destdir}}"/usr/share/dotnet-source/shared/Microsoft.NETCore.App "${{targets.subpkgdir}}"/usr/share/dotnet-source/shared/
    dependencies:
      runtime:
        - dotnet-source-8

  - name: dotnet-source-8-runtime-default
    dependencies:
      runtime:
        - dotnet-source-8-runtime
      provides:
        - dotnet-source-runtime=8

  - name: aspnet-source-8-runtime
    description: "The ASP.NET Core Runtime, version 8"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/dotnet-source/shared
          mv "${{targets.destdir}}"/usr/share/dotnet-source/shared/Microsoft.AspNetCore.App "${{targets.subpkgdir}}"/usr/share/dotnet-source/shared/
    dependencies:
      runtime:
        - dotnet-source-8-runtime

  - name: aspnet-source-8-runtime-default
    dependencies:
      runtime:
        - aspnet-source-8-runtime
      provides:
        - aspnet-source-runtime=8

  - name: dotnet-source-8-targeting-pack
    description: "The .NET Core targeting pack, version 8"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/dotnet-source/packs
          mv "${{targets.destdir}}"/usr/share/dotnet-source/packs/NETStandard.Library.* "${{targets.subpkgdir}}"/usr/share/dotnet-source/packs/
          mv "${{targets.destdir}}"/usr/share/dotnet-source/packs/Microsoft.NETCore.App.* "${{targets.subpkgdir}}"/usr/share/dotnet-source/packs/

  - name: aspnet-source-8-targeting-pack
    description: "The ASP.NET targeting pack, version 8"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/dotnet-source/packs
          mv "${{targets.destdir}}"/usr/share/dotnet-source/packs/Microsoft.AspNetCore.App.* "${{targets.subpkgdir}}"/usr/share/dotnet-source/packs/
    dependencies:
      runtime:
        - dotnet-source-8-targeting-pack

  - name: dotnet-source-8-sdk
    description: "The .NET Core SDK, version 8"
    pipeline:
      - runs: |
          mkdir -p "${{targets.subpkgdir}}"/usr/share/dotnet-source

          for i in sdk sdk-manifests templates; do
            mv "${{targets.destdir}}"/usr/share/dotnet-source/$i "${{targets.subpkgdir}}"/usr/share/dotnet-source/
          done
    dependencies:
      runtime:
        - dotnet-source-8-runtime
        - aspnet-source-8-runtime
        - dotnet-source-8-targeting-pack
        - aspnet-source-8-targeting-pack

  - name: dotnet-source-8-sdk-default
    dependencies:
      runtime:
        - dotnet-source-8-sdk
        - dotnet-source-8-runtime-default
        - aspnet-source-8-runtime-default
      provides:
        - dotnet-sdk-source=8

update:
  enabled: true
  github:
    identifier: dotnet/dotnet
    strip-prefix: v
    use-tag: true
    tag-filter: "v8"

test:
  environment:
    contents:
      packages:
        - dotnet-source-8-sdk
  pipeline:
    - name: Basic .NET command test
      runs: |
        dotnet --info
    - name: Compile and run a simple .NET application
      runs: |
        cat <<'EOF' > HelloWorld.cs
        using System;

        class Program
        {
            static void Main()
            {
                Console.WriteLine("Hello, World!");
            }
        }
        EOF
        dotnet new console -o HelloWorldApp --force
        mv HelloWorld.cs HelloWorldApp/Program.cs
        dotnet run --project HelloWorldApp
    - name: Compile and run a .NET application with arguments
      runs: |
        cat <<'EOF' > ArgumentEcho.cs
        using System;

        class Program
        {
            static void Main(string[] args)
            {
                Console.WriteLine("Arguments: " + String.Join(", ", args));
            }
        }
        EOF
        dotnet new console -o ArgumentEchoApp --force
        mv ArgumentEcho.cs ArgumentEchoApp/Program.cs
        dotnet run --project ArgumentEchoApp -- arg1 arg2 arg3
