package:
  name: powershell
  version: 7.4.6
  epoch: 2
  description: 'cross-platform automation and configuration tool/framework'
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - dotnet-sdk-8.0.404
      - libpsl-native
      - ncurses-terminfo-base

environment:
  contents:
    packages:
      - dotnet-sdk-8.0.404
      - build-base
      - icu-dev
      - krb5-dev
      - libpsl-native
      - lttng-ust-dev
      - openssl-dev
      - wolfi-base
      - zlib-dev
      - dotnet-bootstrap-8

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/powershell/powershell
      branch: release/v7.4
      depth: -1
      destination: powershell

  - working-directory: /home/build/powershell
    pipeline:
      - runs: |
          rm -f global.json
          ln -sf /usr/share/dotnet-bootstrap/dotnet .dotnet
          mkdir -p prereqs/packages/archive/
          ln -sf /usr/share/dotnet-bootstrap/Private.SourceBuilt.Artifacts.Bootstrap.tar.gz prereqs/packages/archive/Private.SourceBuilt.Artifacts.Bootstrap.tar.gz
          mkdir -p prereqs/packages/previously-source-built
          tar -xzvf prereqs/packages/archive/Private.SourceBuilt.Artifacts.Bootstrap.tar.gz -C prereqs/packages/previously-source-built/
      - runs: |
          dotnet restore src/powershell-unix -p:NuGetAudit=false \
            /p:CustomPrebuiltSourceBuiltPackagesPath=$(realpath prereqs/packages/previously-source-built)
          dotnet restore src/ResGen \
            /p:CustomPrebuiltSourceBuiltPackagesPath=$(realpath prereqs/packages/previously-source-built)
          dotnet restore src/TypeCatalogGen \
            /p:CustomPrebuiltSourceBuiltPackagesPath=$(realpath prereqs/packages/previously-source-built)
      - runs: |
          cp /home/build/dependency-gatherer.targets "src/Microsoft.PowerShell.SDK/obj/Microsoft.PowerShell.SDK.csproj.TypeCatalog.targets"
          dotnet msbuild src/Microsoft.PowerShell.SDK/Microsoft.PowerShell.SDK.csproj \
                /t:_GetDependencies \
                "/property:DesignTimeBuild=true;_DependencyFile=$PWD/src/TypeCatalogGen/powershell.inc" \
                /nologo \
                /p:CustomPrebuiltSourceBuiltPackagesPath=$(realpath prereqs/packages/previously-source-built)
          echo v${{package.version}} > powershell.version
      - working-directory: /home/build/powershell/src/ResGen
        runs: |
          dotnet run
      - working-directory: /home/build/powershell/src/TypeCatalogGen
        runs: |
          dotnet run ../System.Management.Automation/CoreCLR/CorePsTypeCatalog.cs powershell.inc
      - runs: |
          dotnet publish --configuration Linux "src/powershell-unix/" \
                --output bin \
                --no-self-contained \
                --runtime "$(dotnet --info | awk '$1=="RID:"{print $2}')" \
                -p:NuGetAudit=false \
                -p:PublishReadyToRun=true /v:n \
                /consoleLoggerParameters:ShowTimestamp \
                /p:CustomPrebuiltSourceBuiltPackagesPath=$(realpath prereqs/packages/previously-source-built)
      - runs: |
          # directory creation
          install -dm 755 "${{targets.destdir}}"/usr/lib "${{targets.destdir}}"/usr/bin

          # library copy
          cp -ar /home/build/powershell/src/powershell-unix/bin/Linux/*/wolfi* "${{targets.destdir}}"/usr/lib/${{package.name}}

          # already provided by 'libpsl-native' aport
          rm -f "${{targets.destdir}}"/usr/lib/$pkgname/libpsl-native.so
          rm -f "${{targets.destdir}}"/usr/lib/$pkgname/libSystem.IO.Ports.Native.so

          # binary link
          ln -s "/usr/lib/${{package.name}}/pwsh" "${{targets.destdir}}"/usr/bin/pwsh

update:
  enabled: true
  github:
    identifier: powershell/powershell
    strip-prefix: v

test:
  pipeline:
    # AUTOGENERATED
    - runs: |
        pwsh --version
        pwsh --help
